import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from 'react';
import Header from './components/Header';
import Footer from './components/Footer';
import { AuthProvider } from '../contexts/AuthContext';
import { ServicesProvider } from '../contexts/ServicesContext';
import { ToastProvider } from '../contexts/ToastContext';
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FixU",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <ToastProvider>
          <AuthProvider>
            <ServicesProvider>
              <Header />
              <main className="flex-grow">
                {children}
              </main>
              <Footer />
            </ServicesProvider>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
